# Common configuration shared by all applications
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example: INFO

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mvc:
    throw-exception-if-no-handler-found: true
  rabbitmq:
    host: 52.53.165.26
    port: 5672
    username: admin
    password: admin123
