import { ApiProjectService } from '../src/services/api/ApiProjectService';
import { mockProjects } from '../src/data/mock/mockProjects';

async function seedProjects() {
  const apiService = new ApiProjectService();
  
  console.log('Starting to seed projects...');
  
  for (const project of mockProjects) {
    try {
      // Remove the id since it will be generated by the backend
      const { id, createdAt, updatedAt, ...projectData } = project;
      
      console.log(`Creating project: ${projectData.name}`);
      const createdProject = await apiService.createProject(projectData);
      console.log(`Successfully created project: ${createdProject.name} with ID: ${createdProject.id}`);
    } catch (error) {
      console.error(`Failed to create project ${project.name}:`, error);
    }
  }
  
  console.log('Finished seeding projects');
}

seedProjects().catch(console.error);
