export const professionalCompetencies: string[] = [
    'Java Enterprise Architecture & System Design',
    'Microservices Architecture',
    'Cloud-Native Application Development',
    'DevOps & CI/CD Pipeline Engineering',
    'API Design & RESTful Services',
    'Distributed Systems & Event-Driven Architecture',
    'Message Broker Integration & Asynchronous Processing (Kafka, RabbitMQ, JMS)',
    'Identity & Access Management',
    'Database Architecture & Optimization',
    'Containerization & Orchestration (Docker, Kubernetes)',
    'Test-Driven Development & Quality Assurance',
    'Full-Stack Development (Java, Spring, React)',
    'Service-Oriented Architecture (SOA)',
    'Data Integration & ETL Processes',
    'SQL & NoSQL Database Technologies',
    'ORM Framework Implementation & Data Persistence (Hibernate, JPA)',
    'Technical Leadership & Mentoring',
    'Modern Web UI Design & Implementation (React, Material UI, Accessibility/WCAG)'
];
