export const professionalCompetencies: string[] = [
    'Technical Design',
    'Project Management',
    'Transaction Processing',
    'Web Programming',
    'API Development',
    'UML/Database Modeling',
    'JavaScript',
    'Continuous Integration & Deployment',
    'Unit Testing',
    'Integration Testing',
    'Black Box/White Box Testing',
    'Performance Optimization',
    'Security Management',
    'Agile/Scrum',
    'Microservices',
    'Amazon Cloud Services (AWS)',
    'Full Stack Development',
    'User Interface development'
];
