AWSTemplateFormatVersion: '2010-09-09'
Description: 'API Gateway setup for AWS Starter API with HTTPS and rate limiting'

Parameters:
  EC2InstanceIP:
    Type: String
    Default: 13.52.157.48
    Description: IP address of the EC2 instance running the Spring Boot API
  
  EC2Port:
    Type: String
    Default: 8080
    Description: Port on which the Spring Boot API is running

Resources:
  # API Gateway REST API
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: aws-starter-api-gateway
      Description: API Gateway for AWS Starter Spring Boot API
      EndpointConfiguration:
        Types:
          - REGIONAL

  # API Gateway Resource (root path)
  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: '{proxy+}'

  # API Gateway Method (ANY)
  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: ANY
        Uri: !Sub 'http://${EC2InstanceIP}:${EC2Port}/{proxy}'
        RequestParameters:
          integration.request.path.proxy: 'method.request.path.proxy'
        IntegrationResponses:
          - StatusCode: 200
      RequestParameters:
        method.request.path.proxy: true

  # Root Method (ANY)
  RootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !GetAtt ApiGateway.RootResourceId
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: ANY
        Uri: !Sub 'http://${EC2InstanceIP}:${EC2Port}/'
        IntegrationResponses:
          - StatusCode: 200

  # API Gateway Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiMethod
      - RootMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: prod

  # Usage Plan for Rate Limiting
  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: ApiDeployment
    Properties:
      UsagePlanName: aws-starter-usage-plan
      Description: Usage plan with rate limiting for AWS Starter API
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: prod
      Throttle:
        RateLimit: 20
        BurstLimit: 40
      Quota:
        Limit: 86400  # 86,400 requests per day (1 request per second on average)
        Period: DAY



Outputs:
  ApiGatewayUrl:
    Description: URL of the API Gateway
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/'
